// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed_unfollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const feedUnFollow = `-- name: FeedUnFollow :exec
DELETE FROM feed_follows
WHERE user_id = $1 and feed_id = $2
`

type FeedUnFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) FeedUnFollow(ctx context.Context, arg FeedUnFollowParams) error {
	_, err := q.db.ExecContext(ctx, feedUnFollow, arg.UserID, arg.FeedID)
	return err
}
